services:
  zipcode-polygons:
    image: postgis/postgis:latest
    container_name: postgres_zipcode_polygons
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zipcode_polygons
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # initialize with SQL
    ports:
      - "5433:5432"

volumes:
  pg_data:
    driver: local
